// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CCHandshakePack.proto

#ifndef PROTOBUF_CCHandshakePack_2eproto__INCLUDED
#define PROTOBUF_CCHandshakePack_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace Models {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CCHandshakePack_2eproto();
void protobuf_AssignDesc_CCHandshakePack_2eproto();
void protobuf_ShutdownFile_CCHandshakePack_2eproto();

class CCHandshakePack;
class CCHandshakeAckPack;

// ===================================================================

class CCHandshakePack : public ::google::protobuf::MessageLite {
 public:
  CCHandshakePack();
  virtual ~CCHandshakePack();
  
  CCHandshakePack(const CCHandshakePack& from);
  
  inline CCHandshakePack& operator=(const CCHandshakePack& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const CCHandshakePack& default_instance();
  
  void Swap(CCHandshakePack* other);
  
  // implements Message ----------------------------------------------
  
  CCHandshakePack* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CCHandshakePack& from);
  void MergeFrom(const CCHandshakePack& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string ver = 1;
  inline bool has_ver() const;
  inline void clear_ver();
  static const int kVerFieldNumber = 1;
  inline const ::std::string& ver() const;
  inline void set_ver(const ::std::string& value);
  inline void set_ver(const char* value);
  inline void set_ver(const char* value, size_t size);
  inline ::std::string* mutable_ver();
  inline ::std::string* release_ver();
  
  // optional string timestamp = 2;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 2;
  inline const ::std::string& timestamp() const;
  inline void set_timestamp(const ::std::string& value);
  inline void set_timestamp(const char* value);
  inline void set_timestamp(const char* value, size_t size);
  inline ::std::string* mutable_timestamp();
  inline ::std::string* release_timestamp();
  
  // @@protoc_insertion_point(class_scope:Models.CCHandshakePack)
 private:
  inline void set_has_ver();
  inline void clear_has_ver();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();
  
  ::std::string* ver_;
  ::std::string* timestamp_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_CCHandshakePack_2eproto();
  friend void protobuf_AssignDesc_CCHandshakePack_2eproto();
  friend void protobuf_ShutdownFile_CCHandshakePack_2eproto();
  
  void InitAsDefaultInstance();
  static CCHandshakePack* default_instance_;
};
// -------------------------------------------------------------------

class CCHandshakeAckPack : public ::google::protobuf::MessageLite {
 public:
  CCHandshakeAckPack();
  virtual ~CCHandshakeAckPack();
  
  CCHandshakeAckPack(const CCHandshakeAckPack& from);
  
  inline CCHandshakeAckPack& operator=(const CCHandshakeAckPack& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const CCHandshakeAckPack& default_instance();
  
  void Swap(CCHandshakeAckPack* other);
  
  // implements Message ----------------------------------------------
  
  CCHandshakeAckPack* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CCHandshakeAckPack& from);
  void MergeFrom(const CCHandshakeAckPack& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 client_id = 1;
  inline bool has_client_id() const;
  inline void clear_client_id();
  static const int kClientIdFieldNumber = 1;
  inline ::google::protobuf::int32 client_id() const;
  inline void set_client_id(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:Models.CCHandshakeAckPack)
 private:
  inline void set_has_client_id();
  inline void clear_has_client_id();
  
  ::google::protobuf::int32 client_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_CCHandshakePack_2eproto();
  friend void protobuf_AssignDesc_CCHandshakePack_2eproto();
  friend void protobuf_ShutdownFile_CCHandshakePack_2eproto();
  
  void InitAsDefaultInstance();
  static CCHandshakeAckPack* default_instance_;
};
// ===================================================================


// ===================================================================

// CCHandshakePack

// optional string ver = 1;
inline bool CCHandshakePack::has_ver() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CCHandshakePack::set_has_ver() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CCHandshakePack::clear_has_ver() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CCHandshakePack::clear_ver() {
  if (ver_ != &::google::protobuf::internal::kEmptyString) {
    ver_->clear();
  }
  clear_has_ver();
}
inline const ::std::string& CCHandshakePack::ver() const {
  return *ver_;
}
inline void CCHandshakePack::set_ver(const ::std::string& value) {
  set_has_ver();
  if (ver_ == &::google::protobuf::internal::kEmptyString) {
    ver_ = new ::std::string;
  }
  ver_->assign(value);
}
inline void CCHandshakePack::set_ver(const char* value) {
  set_has_ver();
  if (ver_ == &::google::protobuf::internal::kEmptyString) {
    ver_ = new ::std::string;
  }
  ver_->assign(value);
}
inline void CCHandshakePack::set_ver(const char* value, size_t size) {
  set_has_ver();
  if (ver_ == &::google::protobuf::internal::kEmptyString) {
    ver_ = new ::std::string;
  }
  ver_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CCHandshakePack::mutable_ver() {
  set_has_ver();
  if (ver_ == &::google::protobuf::internal::kEmptyString) {
    ver_ = new ::std::string;
  }
  return ver_;
}
inline ::std::string* CCHandshakePack::release_ver() {
  clear_has_ver();
  if (ver_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ver_;
    ver_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string timestamp = 2;
inline bool CCHandshakePack::has_timestamp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CCHandshakePack::set_has_timestamp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CCHandshakePack::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CCHandshakePack::clear_timestamp() {
  if (timestamp_ != &::google::protobuf::internal::kEmptyString) {
    timestamp_->clear();
  }
  clear_has_timestamp();
}
inline const ::std::string& CCHandshakePack::timestamp() const {
  return *timestamp_;
}
inline void CCHandshakePack::set_timestamp(const ::std::string& value) {
  set_has_timestamp();
  if (timestamp_ == &::google::protobuf::internal::kEmptyString) {
    timestamp_ = new ::std::string;
  }
  timestamp_->assign(value);
}
inline void CCHandshakePack::set_timestamp(const char* value) {
  set_has_timestamp();
  if (timestamp_ == &::google::protobuf::internal::kEmptyString) {
    timestamp_ = new ::std::string;
  }
  timestamp_->assign(value);
}
inline void CCHandshakePack::set_timestamp(const char* value, size_t size) {
  set_has_timestamp();
  if (timestamp_ == &::google::protobuf::internal::kEmptyString) {
    timestamp_ = new ::std::string;
  }
  timestamp_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CCHandshakePack::mutable_timestamp() {
  set_has_timestamp();
  if (timestamp_ == &::google::protobuf::internal::kEmptyString) {
    timestamp_ = new ::std::string;
  }
  return timestamp_;
}
inline ::std::string* CCHandshakePack::release_timestamp() {
  clear_has_timestamp();
  if (timestamp_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = timestamp_;
    timestamp_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// CCHandshakeAckPack

// optional int32 client_id = 1;
inline bool CCHandshakeAckPack::has_client_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CCHandshakeAckPack::set_has_client_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CCHandshakeAckPack::clear_has_client_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CCHandshakeAckPack::clear_client_id() {
  client_id_ = 0;
  clear_has_client_id();
}
inline ::google::protobuf::int32 CCHandshakeAckPack::client_id() const {
  return client_id_;
}
inline void CCHandshakeAckPack::set_client_id(::google::protobuf::int32 value) {
  set_has_client_id();
  client_id_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Models

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CCHandshakePack_2eproto__INCLUDED
